# .github/workflows/ci.yml
name: Application CI

on:
  push:
    branches: [ "main" ] # Runs on pushes to the main branch
  pull_request:
    branches: [ "main" ] # Runs on pull requests targeting main

jobs:
  initial-setup-check:
    name: CI Setup Check
    runs-on: ubuntu-latest # Specifies the type of machine to run the job on
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Echo success message
        run: echo "✅ CI Pipeline scaffold is set up and running correctly!"